export enum languageCodeToName {
  "Hindi",
  "Bengali",
  "Telugu",
  "Marathi",
  "Tamil",
  "Urdu",
  "Gujarati",
  "Kannada",
  "Odia",
  "Punjabi",
  "Malayalam",
  "Assamese",
  "Maithili",
  "Sanskrit",
  "Kashmiri",
  "Nepali",
  "Sindhi",
  "Konkani",
  "Dogri",
  "Manipuri",
  "Bodo",
  "Santhali",
  "Sourashtra",
  "Khasi",
  "Mizo",
  "Garhwali",
  "Kumaoni",
  "Nagamese",
  "English",
}

export enum CategoryCodeToName{
  "Health & Wellness",
  "Tutors & Coaches",
  "Parlour & Spa",
  "Task Master",
  "Design & Construction",
  "Vehicle & Transportation",
  "Restaurant & Food"
}
